version: 2.1
jobs:
  build:
    docker:
      - image: docker:stable
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build images and push
          command: |
            export PHP_BASE_TAG="php:7.4-fpm-alpine"
            docker build -f base/Dockerfile -t "${DOCKERHUB_USERNAME}/${PHP_BASE_TAG}" base
            docker build -f wordpress/Dockerfile -t "${DOCKERHUB_USERNAME}/${PHP_BASE_TAG}-wordpress" wordpress
            docker build -f drupal/Dockerfile -t "${DOCKERHUB_USERNAME}/${PHP_BASE_TAG}-drupal" drupal
            echo "${DOCKERHUB_PASSWORD}" | docker login -u "${DOCKERHUB_USERNAME}" --password-stdin
            docker push "${DOCKERHUB_USERNAME}/${PHP_BASE_TAG}"
            docker push "${DOCKERHUB_USERNAME}/${PHP_BASE_TAG}-wordpress"
            docker push "${DOCKERHUB_USERNAME}/${PHP_BASE_TAG}-drupal"
workflows:
  build:
    jobs:
      - build:
          filters:
            branches:
              only: master